apiVersion: v2
name: tornjak-frontend
description: A Helm chart to deploy Tornjak frontend
type: application
version: 0.1.0
appVersion: "v2.1.0"
home: https://github.com/daescha/helm-charts-hardened/tree/helm-repo/charts/spire
sources:
  - https://github.com/spiffe/tornjak
icon: https://raw.githubusercontent.com/spiffe/tornjak/main/logos/logo%2Btornjak.2132x1291.png
maintainers:
  - name: mrsabath
    email: mrsabath@gmail.com
    url: https://mrsabath.github.io
