name: Release Helm Charts

on:
  push:
    branches:
      - helm-repo
    paths:
      - '.github/workflows/helm-release.yml'
      - 'charts/**'

jobs:
  release:
    runs-on: ubuntu-22.04

    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Setup cosign
        uses: sigstore/cosign-installer@v3.4.0
        with:
          cosign-release: v2.2.3

      - name: Set up Helm
        uses: azure/setup-helm@v3.5
        with:
          version: v3.10.3

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
